[package]
name = "oasis-runtime-sdk"
version = "0.1.0"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
cbor = { version = "0.1.3", package = "oasis-cbor" }
# TODO: Replace with released version once it includes https://github.com/oasisprotocol/oasis-core/pull/4133.
oasis-core-runtime = { git = "https://github.com/oasisprotocol/oasis-core", rev = "a1c9fe982c32d550e8eac530bf8e79402728d64a" }
oasis-runtime-sdk-macros = { path = "../runtime-sdk-macros", optional = true }

# Third party.
curve25519-dalek = "3.2.0"
sha2 = "0.9.3"
k256 = { version = "0.9.6" }
schnorrkel = "0.10.1"
thiserror = "1.0.26"
hex = "0.4.2"
io-context = "0.2.0"
anyhow = "1.0.42"
bech32 = "0.8.1"
num-traits = "0.2.14"
impl-trait-for-tuples = "0.2.1"
base64 = "0.13.0"
once_cell = "1.8.0"
slog = "2.7.0"

[features]
default = ["oasis-runtime-sdk-macros"]
unsafe-allow-debug = []
